name: MatterHubs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    env:
      PUBLIC_SHOPIFY_API_SECRET_KEY: ${{ secrets.PUBLIC_SHOPIFY_API_SECRET_KEY }}
      PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN: ${{secrets.PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN }}
      PUBLIC_SHOPIFY_STORE_DOMAIN: ${{secrets.PUBLIC_SHOPIFY_STORE_DOMAIN }}
      JUDGEME_SHOP_DOMAIN: ${{secrets.JUDGEME_SHOP_DOMAIN }}
      JUDGEME_API_TOKEN: ${{secrets.JUDGEME_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm i
      - name: Build Astro Site
        run: npm run build
      
      - name: Deploy everything
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Stop the service
            sudo systemctl stop matterhubs || true
            
            # Create deployment directory if it doesn't exist
            mkdir -p /var/www/dev.matterhubs.com
            cd /var/www/dev.matterhubs.com
            
            # Remove old files except node_modules
            find . -maxdepth 1 ! -name 'node_modules' ! -name '.' -exec rm -rf {} +
      
      - name: Copy package files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "package.json,package-lock.json"
          target: "/var/www/dev.matterhubs.com"
          overwrite: true
      
      - name: Copy build files  
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist"
          target: "/var/www/dev.matterhubs.com"
          overwrite: true
      
      - name: Setup and start service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/dev.matterhubs.com
            
            # Debug - check what we have
            echo "=== Directory contents ==="
            ls -la
            echo "=== Package.json exists? ==="
            test -f package.json && echo "YES" || echo "NO"
            
            # Move build files to root
            if [ -d "dist" ]; then
              mv dist/* . 2>/dev/null || true
              rmdir dist 2>/dev/null || true
            fi
            
            # Install dependencies
            if [ -f package.json ]; then
              npm i --omit=dev
            else
              echo "ERROR: package.json not found!"
              exit 1
            fi
            
            # Start service
            sudo systemctl start matterhubs
            sleep 3
            sudo systemctl status matterhubs --no-pager
            sudo systemctl reload nginx
